name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 执行
  workflow_dispatch: # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the forked repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your-email@example.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main

      - name: Push changes to fork
        run: git push origin main
        # 如果你的主分支不是 `main`，请相应修改
